# Generated by Django 5.2.1 on 2025-05-27 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mythology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre de la Mythologie')),
                ('slug', models.SlugField(blank=True, help_text='Identifiant URL (auto-généré à partir du titre si laissé vide)', max_length=110, unique=True)),
                ('icon_class', models.CharField(help_text="Classe Font Awesome (ex: 'fa-dragon')", max_length=50)),
                ('color_from', models.CharField(help_text="Classe Tailwind pour début gradient (ex: 'from-red-500')", max_length=50)),
                ('color_to', models.CharField(help_text="Classe Tailwind pour fin gradient (ex: 'to-yellow-400')", max_length=50)),
                ('description', models.TextField(verbose_name='Description Complète')),
                ('card_summary', models.CharField(blank=True, help_text='Texte court pour la carte principale (optionnel)', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Mythologie',
                'verbose_name_plural': 'Mythologies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Personnage')),
                ('slug', models.SlugField(blank=True, help_text='Identifiant URL (auto-généré, unique par mythologie)', max_length=110)),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='Rôle principal')),
                ('description', models.TextField(blank=True, verbose_name='Description du Personnage')),
                ('image_url', models.URLField(blank=True, help_text="URL de l'image du personnage (ex: Imgur)", max_length=300, null=True)),
                ('mythology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='mythpedia.mythology')),
            ],
            options={
                'verbose_name': 'Personnage',
                'verbose_name_plural': 'Personnages',
                'ordering': ['mythology', 'name'],
                'unique_together': {('mythology', 'slug')},
            },
        ),
    ]
