# Generated by Django 5.2.1 on 2025-06-15 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythpedia', '0003_favoritecharacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL de l'image", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identifiant URL (auto-généré)', max_length=110),
        ),
        migrations.AlterField(
            model_name='favoritecharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users_char', to='mythpedia.character'),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='card_summary',
            field=models.CharField(blank=True, help_text='Résumé pour carte', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='color_from',
            field=models.CharField(help_text='Classe Tailwind début gradient', max_length=50),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='color_to',
            field=models.CharField(help_text='Classe Tailwind fin gradient', max_length=50),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='icon_class',
            field=models.CharField(help_text='Classe Font Awesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identifiant URL (auto-généré)', max_length=110, unique=True),
        ),
        migrations.CreateModel(
            name='MythStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du Mythe/Récit')),
                ('slug', models.SlugField(blank=True, help_text='Identifiant URL (auto-généré, unique par mythologie)', max_length=220)),
                ('summary', models.TextField(help_text="Un bref aperçu de l'histoire.", verbose_name='Résumé Concis')),
                ('full_text', models.TextField(blank=True, help_text='Le récit détaillé du mythe.', null=True, verbose_name='Texte Complet du Récit')),
                ('themes', models.CharField(blank=True, help_text='Thèmes principaux (ex: création, amour, trahison), séparés par des virgules.', max_length=255, null=True)),
                ('published_on', models.DateTimeField(auto_now_add=True, verbose_name='Publié le')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('key_characters', models.ManyToManyField(blank=True, related_name='featured_in_stories', to='mythpedia.character', verbose_name='Personnages Clés')),
                ('mythology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='mythpedia.mythology', verbose_name='Mythologie Associée')),
            ],
            options={
                'verbose_name': 'Mythe / Récit',
                'verbose_name_plural': 'Mythes / Récits',
                'ordering': ['mythology', 'title'],
                'unique_together': {('mythology', 'slug')},
            },
        ),
    ]
