# Generated by Django 5.2.1 on 2025-06-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythpedia', '0004_alter_character_image_url_alter_character_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemythology',
            options={'ordering': ['-added_on'], 'verbose_name': 'Mythologie Favorite', 'verbose_name_plural': 'Mythologies Favorites'},
        ),
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL de l'image du personnage (ex: Imgur)", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identifiant URL (auto-généré, unique par mythologie)', max_length=110),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='card_summary',
            field=models.CharField(blank=True, help_text='Résumé pour carte (optionnel)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='color_from',
            field=models.CharField(help_text="Classe Tailwind début gradient (ex: 'from-red-500')", max_length=50),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='color_to',
            field=models.CharField(help_text="Classe Tailwind fin gradient (ex: 'to-yellow-400')", max_length=50),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='icon_class',
            field=models.CharField(help_text="Classe Font Awesome (ex: 'fa-dragon')", max_length=50),
        ),
        migrations.DeleteModel(
            name='MythStory',
        ),
    ]
