# Generated by Django 5.2.1 on 2025-06-15 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythpedia', '0005_alter_favoritemythology_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemythology',
            options={'ordering': ['-added_on']},
        ),
        migrations.AlterField(
            model_name='favoritecharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='mythpedia.character'),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='card_summary',
            field=models.CharField(blank=True, help_text='Texte court pour la carte principale (optionnel)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='color_from',
            field=models.CharField(help_text="Classe Tailwind pour début gradient (ex: 'from-red-500')", max_length=50),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='color_to',
            field=models.CharField(help_text="Classe Tailwind pour fin gradient (ex: 'to-yellow-400')", max_length=50),
        ),
        migrations.AlterField(
            model_name='mythology',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identifiant URL (auto-généré à partir du titre si laissé vide)', max_length=110, unique=True),
        ),
    ]
