# Generated by Django 5.2.1 on 2025-06-17 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythpedia', '0006_alter_favoritemythology_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritemythology',
            options={'ordering': ['-added_on'], 'verbose_name': 'Mythologie Favorite', 'verbose_name_plural': 'Mythologies Favorites'},
        ),
        migrations.AlterField(
            model_name='favoritecharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_user_set', to='mythpedia.character'),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_email', models.CharField(blank=True, help_text='Votre nom ou email (si non connecté ou pour contact)', max_length=150)),
                ('submission_type', models.CharField(choices=[('MYTHOLOGY', 'Nouvelle Mythologie'), ('CHARACTER', 'Nouveau Personnage'), ('CORRECTION', "Correction/Ajout d'Information"), ('OTHER', 'Autre Suggestion')], max_length=20, verbose_name='Type de Suggestion')),
                ('title', models.CharField(help_text="Ex: 'Ajouter la Mythologie Sumérienne' ou 'Correction sur Zeus'", max_length=200, verbose_name='Titre/Sujet de la Suggestion')),
                ('description', models.TextField(verbose_name='Détails de la Suggestion')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REVIEWED', "En cours d'examen"), ('APPROVED', 'Approuvée'), ('IMPLEMENTED', 'Implémentée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('submitted_on', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name="Notes de l'Administrateur")),
                ('related_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_suggestions_char', to='mythpedia.character', verbose_name='Personnage Concerné (si applicable)')),
                ('related_mythology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_suggestions_myth', to='mythpedia.mythology', verbose_name='Mythologie Concernée (si applicable)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_made', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur (si connecté)')),
            ],
            options={
                'verbose_name': 'Suggestion Utilisateur',
                'verbose_name_plural': 'Suggestions des Utilisateurs',
                'ordering': ['-submitted_on'],
            },
        ),
    ]
